-------------------------------------------------------------------------------------------------------------------------------

# Array

-------------------------------------------------------------------------------------------------------------------------------

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print (a)

[1 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]])    # 2d array
b

array([[1, 2, 3],
       [4, 5, 6]])

-------------------------------------------------------------------------------------------------------------------------------

In [35]:
arr = array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [36]:
arr

array([1, 2, 3, 4, 5])

In [37]:
print(arr.dtype)

int32


In [38]:
# According to concept of Array, All the elements should be of same type
# We have integer & float values together
# All the values here converted into float type

arr = array([1,2,3,4,5.0])
print(arr.dtype)

float64


In [39]:
print(arr)                           # All the values here converted into float type

[1. 2. 3. 4. 5.]


In [40]:
arr = array([1,2,3,4,5],int)         # All the values prints as integer type
print(arr)

[1 2 3 4 5]


In [41]:
arr = array([1,2,3,4,5],float)        # All the values here converted into float type
print(arr)

[1. 2. 3. 4. 5.]


In [49]:
arr1 = array([[1,2,3],[4,5,6]])      # 2d array
print(arr1)

[[1 2 3]
 [4 5 6]]


In [50]:
print(arr1.ndim)

2


In [51]:
print(arr1.shape)       # number of rows & columns

(2, 3)


In [52]:
print(arr1.size)

6


In [59]:
arr2 = array([[1,2,3],[4,5,6]])
arr3 = arr2.flatten()                    # converts 2d array into 1d array
print(arr3)

[1 2 3 4 5 6]


In [77]:
arr = array([1,2,3,4,5])
arr = arr+5
print(arr)

[ 6  7  8  9 10]


In [78]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
arr3 = arr1 + arr2
print(arr3)

[ 7  9 11 13 15]


In [79]:
arr1 = array([1,2,3,4,5])
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [80]:
arr1 = array([1,2,3,4,5])
print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [81]:
arr1 = array([1,2,3,4,5])
print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [82]:
arr1 = array([1,2,3,4,5])
print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [84]:
arr1 = array([1,2,3,4,5])
print(max(arr1))

5


In [83]:
arr1 = array([1,2,3,4,5])
print(sum(arr1))

15


In [85]:
arr1 = array([1,2,3,4,5])
print(min(arr1))

1


In [86]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,7,8,9,10])
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


# Python: NUMPY | Numerical Python Arrays Tutorial
# https://www.youtube.com/watch?v=8Mpc9ukltVA