## Copy

In [1]:
import numpy as np

In [4]:
from numpy import *

In [3]:
arr1 = np.array([2,6,8,1,3])

arr2 = arr1

print(arr1)
print(arr2)

print(id(arr1))    # pointing to same address
print(id(arr2))

[2 6 8 1 3]
[2 6 8 1 3]
2538914464592
2538914464592


In [5]:
arr1 = array([2,6,8,1,3])

arr2 = arr1.view()

print(arr1)
print(arr2)

print(id(arr1))                  # pointing to different address
print(id(arr2))

[2 6 8 1 3]
[2 6 8 1 3]
2538914465152
2538914465072


In [6]:
arr1 = array([2,6,8,1,3])

arr2 = arr1.view()

arr1[1] = 7                   # shallow copy; same values for both arr1 & arr2

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 7 8 1 3]
2538914465392
2538914464432


In [7]:
arr1 = array([2,6,8,1,3])

arr2 = arr1.copy()

arr1[1] = 7                   # deep copy; different values for arr1 & arr2

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 7 8 1 3]
[2 6 8 1 3]
2538914465632
2538914465712
