## Linspace

In [2]:
import numpy as np

In [6]:
from numpy import *

In [9]:
# import numpy as np
# from numpy import *

arr = np.linspace(0,15)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [10]:
# Return evenly spaced numbers over a specified interval.
# Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
# np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)

np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
np.linspace(10,100,10,retstep=True)

(array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]), 10.0)

In [12]:
np.linspace(10,100,12)

array([ 10.        ,  18.18181818,  26.36363636,  34.54545455,
        42.72727273,  50.90909091,  59.09090909,  67.27272727,
        75.45454545,  83.63636364,  91.81818182, 100.        ])

In [13]:
np.linspace(10,100,12,retstep=True)

(array([ 10.        ,  18.18181818,  26.36363636,  34.54545455,
         42.72727273,  50.90909091,  59.09090909,  67.27272727,
         75.45454545,  83.63636364,  91.81818182, 100.        ]),
 8.181818181818182)

In [14]:
np.linspace(10,100,12,retstep=False)

array([ 10.        ,  18.18181818,  26.36363636,  34.54545455,
        42.72727273,  50.90909091,  59.09090909,  67.27272727,
        75.45454545,  83.63636364,  91.81818182, 100.        ])

In [15]:
np.linspace(10,100,25)

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [16]:
print(np.linspace(10,15,10))

[10.         10.55555556 11.11111111 11.66666667 12.22222222 12.77777778
 13.33333333 13.88888889 14.44444444 15.        ]
