## Matrix

In [2]:
import numpy as np

In [4]:
from numpy import *

In [5]:
# Method:1 to generate Matrix

arr1 = array([[1,2,3],[4,5,6]])      # 2d array
m = matrix(arr1)
print(m)

[[1 2 3]
 [4 5 6]]


In [6]:
# Method:2 to generate Matrix

m1 = matrix('1 2 3 4 ; 5 6 7 8')
print(m1)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
m1 = matrix('1 2 ; 3 4 ; 5 6 ; 7 8')
print(m1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')          # diagonal matrix
print(diagonal(m1))

[1 5 9]


In [9]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')          # max element in matrix
print(m1.max())

9


In [10]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')          # min element in matrix
print(m1.min())

1


In [11]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m2 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m3 = m1 + m2                                   # matrix addition
print(m3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
m1 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m2 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m3 = m1 * m2                                   # matrix multiplication
print(m3)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
