-------------------------------------------------------------------------------------------------------------------------------

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])               # 1d array

print(a.ndim)

1


In [2]:
a = np.array([(1,2,3),(2,3,4)])      # 2d array

print(a.ndim)

2


-------------------------------------------------------------------------------------------------------------------------------

In [4]:
print(a.itemsize)    # each element occupies 4 bytes

4


-------------------------------------------------------------------------------------------------------------------------------

In [5]:
print(a.dtype)

int32


-------------------------------------------------------------------------------------------------------------------------------

In [6]:
a = np.array([1,2,3,4,5,6,7])

print(a.size)

7


In [7]:
a = np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])

print(a.size)

14


-------------------------------------------------------------------------------------------------------------------------------

In [8]:
a = np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])      # number of rows & columns

print(a.shape)

(2, 7)


-------------------------------------------------------------------------------------------------------------------------------

In [9]:
a = np.array([(1,2,3),(4,5,6)])

print(a.sum(axis=0))                                       # sum of each column elements

[5 7 9]


In [10]:
a = np.array([(1,2,3),(4,5,6)])

print(a.sum(axis=1))                                        # sum of each row elements

[ 6 15]


-------------------------------------------------------------------------------------------------------------------------------

In [11]:
a = np.array([(1,2,3),(4,5,6)])

print(np.sqrt(a))                                           # square root of each of the element

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


-------------------------------------------------------------------------------------------------------------------------------

In [12]:
a = np.array([(1,2,3),(4,5,6)])

print(np.std(a))

1.707825127659933


-------------------------------------------------------------------------------------------------------------------------------

In [13]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])

print(a+b)

[[ 2  4  6]
 [ 8 10 12]]


In [14]:
print(a-b)

[[0 0 0]
 [0 0 0]]


In [15]:
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [16]:
print(a/b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [18]:
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [19]:
print(a.ravel())                                      # converting to single column

[1 2 3 4 5 6]
