In [1]:
import numpy as np

In [12]:
from numpy import *

### 1. Zeros
### 2. Ones
### 3. Empty
### 4. Logspace
### 5. Trace

## 1. Zeros

-------------------------------------------------------------------------------------------------------------------------------

In [15]:
# array with zeros

array_with_zeros = np.zeros((3,3))      # array_with_zeros = zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr = np.zeros(5)                       # arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


-------------------------------------------------------------------------------------------------------------------------------

## 2. Ones

-------------------------------------------------------------------------------------------------------------------------------

In [3]:
# array with ones

array_with_ones = np.ones((3,3))          # array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr = np.ones(5)                           # arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [19]:
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


-------------------------------------------------------------------------------------------------------------------------------

## 3. Empty

-------------------------------------------------------------------------------------------------------------------------------

In [4]:
# array with empty

array_with_empty = np.empty((2,3))
array_with_empty

array([[8.20911861e-307, 3.32653204e-111, 7.28297456e+199],
       [1.35507324e+248, 3.05339237e-307, 1.75595879e+243]])

-------------------------------------------------------------------------------------------------------------------------------

## 4. logspace

-------------------------------------------------------------------------------------------------------------------------------

In [20]:
arr = logspace(1,40,5)
arr

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

-------------------------------------------------------------------------------------------------------------------------------

## 5. Trace

-------------------------------------------------------------------------------------------------------------------------------

In [21]:
trace_array =np.array([[10,20],[22,31]])          # Sum of diagonal elements "10" and "31"
np.trace(trace_array)

41