## Random    ------ Generating random numbers

In [1]:
import numpy as np

In [2]:
a = np.random.random((2,3))
a

array([[0.11385384, 0.12406963, 0.95704105],
       [0.50829276, 0.01874263, 0.49524704]])

In [3]:
np.set_printoptions(precision=2,suppress=True)
a

array([[0.11, 0.12, 0.96],
       [0.51, 0.02, 0.5 ]])

In [4]:
a = np.random.randint(0,10,5)
a

array([5, 0, 8, 4, 8])

In [5]:
b = np.random.randint(1,10,6)
b

array([4, 9, 4, 7, 6, 5])

In [7]:
b = b.reshape(3,2)
b

array([[4, 9],
       [4, 7],
       [6, 5]])

In [9]:
b.sum(axis=1)

array([13, 11, 11])

In [10]:
b.sum(axis=0)

array([14, 21])

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(a)
a

array([7, 0, 3, 4, 2, 8, 1, 5, 6, 9])

In [13]:
np.random.choice(a)         # it gives different item every time

5

In [14]:
np.random.random_integers(5,10,2)

C:\Users\deepusuresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([6, 6])

In [15]:
np.random.randint(5,10,2)

array([8, 7])

-------------------------------------------------------------------------------------------------------------------------------

In [16]:
x1 = np.random.randint(10, size=10)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [17]:
x1.ndim

1

In [18]:
x2.ndim

2

In [19]:
x3.ndim

3

In [20]:
x1.shape

(10,)

In [21]:
x2.shape

(3, 4)

In [22]:
x3.shape

(3, 4, 5)

In [23]:
x1.size

10

In [24]:
x2.size

12

In [25]:
x3.size

60