## Reshape

In [5]:
import numpy as np

In [6]:
x4 = np.arange(12)
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x4 = x4.reshape(2,6)    # 2 rows and 6 columns
x4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
x4 = x4.reshape(3,4)    # 3 rows and 4 columns
x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
x4 = x4.reshape(2,2,3)    # 3d Array(two 2d array & each has 3 values)
x4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [2]:
# 2D (or) two dimensional array

TwoD_array = oneD_array.reshape(3,5)
print(TwoD_array)

NameError: name 'oneD_array' is not defined

In [ ]:
# 3D (or) three dimensional array

ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

In [ ]:
print(np.linspace(4,13,7))