-------------------------------------------------------------------------------------------------------------------------------

## Slicing

-------------------------------------------------------------------------------------------------------------------------------

In [1]:
import numpy as np

In [2]:
a = np.array([(1,2,3,4),(8,9,10,11)])

print(a)

[[ 1  2  3  4]
 [ 8  9 10 11]]


In [3]:
print(a.reshape(4,2))

[[ 1  2]
 [ 3  4]
 [ 8  9]
 [10 11]]


In [5]:
b = np.array([(1,2,3,4),(3,4,5,6)])
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [6]:
print(b[0,2])

3


In [7]:
print(b[0:,3])  # all the rows including 0 & in that rows only index 3 

[4 6]


In [10]:
c = np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])
c

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [11]:
print(c[0:,3])

[ 4  6 10]


In [12]:
print(c[0:2,3])    # 0:2 it won't include 2nd element; includes only 0th & 1st.

[4 6]
