# Python List vs Numpy Array

-------------------------------------------------------------------------------------------------------------------------------

## 1. Array:
 
       a. supports only for one dimensional array.
       b. does not support for multi dimensional array.
       c. In Array all values has to be same type.
       
## 2. Numpy:

       a. supports for both one & multi dimensional array.

          The reason using arrays is that, array operation is fast. Whenever convert my dataset into array, I can take the data applied to my machine learning algorithm such that training takes up quickly. Because of that we extensively using arrays.

-------------------------------------------------------------------------------------------------------------------------------

## Example : 1

In [2]:
# without numpy installing, error will display

distance = [10,15,17,26]
time = [.30, .47, .55, 1.20]

speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
import numpy as np

In [4]:
np_distance = np.array(distance)
np_time = np.array(time)

speed = np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

-------------------------------------------------------------------------------------------------------------------------------

## Example : 2

### Python List

In [6]:
# throughs error because no idea how to do this calculation. In order overcome this (refer next step)

A = [25.6,84.3,12.7,62.8]
B = [5.21,34.3,98.2,46.4]

print(A*B)

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
# lengthy method

print(A[0]*B[0])

133.376


### Numpy

In [9]:
import numpy as np

A = np.array([25.6,84.3,12.7,62.8])
B = np.array([5.21,34.3,98.2,46.4])

print(A)
print(B)
print(A*B)

[25.6 84.3 12.7 62.8]
[ 5.21 34.3  98.2  46.4 ]
[ 133.376 2891.49  1247.14  2913.92 ]


-------------------------------------------------------------------------------------------------------------------------------

## Example : 3

### Python List

In [10]:
List_A = [1,2,3,4]

print(List_A+List_A)

[1, 2, 3, 4, 1, 2, 3, 4]


### Numpy Array

In [11]:
List_A = np.array([1,2,3,4])

print(List_A+List_A)

[2 4 6 8]


-------------------------------------------------------------------------------------------------------------------------------

### Numpy v/s List ---- we will use Numpy instead of List

### Advantages
    # 1.Less Memory
    # 2.Fast
    # 3.Convenient

### 1. It occupies less memory

In [12]:
import time
import sys

In [13]:
S = range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [14]:
D = np.arange(1000)
print(D.size*D.itemsize)

4000


### 2. Numpy Array is fast and Convenient compared to Python List

In [15]:
size = 1000000

# List

L1 = range(size)
L2 = range(size)

start = time.time()

result = [(x,y) for x,y in zip(L1,L2)]

print((time.time()-start)*1000)

# NP Array

A1 = np.arange(size)
A2 = np.arange(size)

start = time.time()

result = A1+A2

print((time.time()-start)*1000)

1196.0036754608154
93.74332427978516
